#!/bin/bash

echo "Stand back. The Juggergrunt is revving up..."
grunt

# Patch in prototype stuff
cp -R app/source ../api/public
cp -R app/assets ../api/public

# Create an un-cache-busted version of profile-default.png for use in some
# hard-coded JavaScript (for now) until I get image uploads in.
cp    ../api/public/images/*profile-default.png ../api/public/images/profile-default.png
